CREATE DATABASE IF NOT EXISTS PROJETOS100;

USE PROJETOS100;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNCIONARIO INT PRIMARY KEY NOT NULL, 
NOME_FUNCIONARIO VARCHAR(70) NOT NULL,
EMAIL_FUNCIONARIO VARCHAR(70) NOT NULL,
CARGO_FUNCIONARIO VARCHAR(20) NOT NULL,
DATANASC_FUNCIONARIO DATE NOT NULL,
RG_FUNCIONARIO VARCHAR(20) NOT NULL,
CPF_FUNCIONARIO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS DONATARIOS(
ID_DONATARIO INT PRIMARY KEY NOT NULL,
CNPJ_DONATARIO VARCHAR(40) NOT NULL,
PESSOACONTATO_DONATARIO VARCHAR(50) NOT NULL,
NOME_DONATARIO VARCHAR(70) NOT NULL,
CPF_DONATARIO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS EDITAL(
ID_EDITAL INT PRIMARY KEY NOT NULL,
INICIO_EDITAL DATE NOT NULL,
FIM_EDITAL DATE NOT NULL,
TEMATICA_EDITAL VARCHAR(45) NOT NULL,
ID_DONATARIO_EDITAL INT NOT NULL,
ID_FUNCIONARIO_EDITAL INT NOT NULL,
CONSTRAINT FK_ID_DONATARIO FOREIGN KEY (ID_DONATARIO_EDITAL) REFERENCES DONATARIOS(ID_DONATARIO),
CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO_EDITAL) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS VISTORIA(
ID_VISTORIA INT PRIMARY KEY NOT NULL,
DOC_VISTORIA VARCHAR(45) NOT NULL,
STATUS_VISTORIA TEXT NOT NULL,
ID_DONATARIO_VISTORIA INT NOT NULL,
ID_FUNCIONARIO_VISTORIA INT NOT NULL,
CONSTRAINT FK_ID_DONATARIO_VISTORIA FOREIGN KEY (ID_DONATARIO_VISTORIA) REFERENCES DONATARIOS(ID_DONATARIO),
CONSTRAINT FK_ID_FUNCIONARIO_VISTORIA FOREIGN KEY (ID_FUNCIONARIO_VISTORIA) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS RELATORIOS(
ID_RELATORIOS INT PRIMARY KEY NOT NULL,
DATA_RELATORIO DATE NOT NULL,
GASTOS_RELATORIO DECIMAL(10,2) NOT NULL,
ID_VISTORIA_RELATORIO INT NOT NULL,
CONSTRAINT FK_ID_VISTORIA_RELATORIO FOREIGN KEY (ID_VISTORIA_RELATORIO) REFERENCES VISTORIA(ID_VISTORIA)
);

CREATE TABLE IF NOT EXISTS REUNIOES(
ID_REUNIAO INT PRIMARY KEY NOT NULL,
DATA_REUNIAO DATE NOT NULL,
HORA_REUNIAO TIME NOT NULL,
ID_VISTORIA_REUNIAO INT NOT NULL,  
CONSTRAINT FK_ID_VISTORIA_REUNIAO FOREIGN KEY (ID_VISTORIA_REUNIAO) REFERENCES VISTORIA(ID_VISTORIA)  	
);

CREATE TABLE IF NOT EXISTS ENDERECOS(
N_RUA_END INT,
RUA_END VARCHAR(45) NOT NULL,
BAIRRO_END VARCHAR(45) NOT NULL,
CIDADE_END VARCHAR(45) NOT NULL,
ESTADO_END VARCHAR(45) NOT NULL,
PAIS_END VARCHAR(45) NOT NULL,
ID_DONATARIO_END INT NOT NULL,
ID_FUNCIONARIO_END INT NOT NULL,
CONSTRAINT FK_ID_DONATARIO_END FOREIGN KEY (ID_DONATARIO_END) REFERENCES DONATARIOS(ID_DONATARIO),
CONSTRAINT FK_ID_FUNCIONARIO_END FOREIGN KEY (ID_FUNCIONARIO_END) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO) 
);

CREATE TABLE IF NOT EXISTS TELEFONES(
DDI_TEL VARCHAR(4) NOT NULL,
DDD_TEL VARCHAR(4) NOT NULL,
NUMERO_TEL VARCHAR(15),
ID_DONATARIO_TEL INT NOT NULL,
ID_FUNCIONARIO_TEL INT NOT NULL,
CONSTRAINT FK_ID_DONATARIO_TEL FOREIGN KEY(ID_DONATARIO_TEL) REFERENCES DONATARIOS(ID_DONATARIO),
CONSTRAINT FK_ID_FUNCIONARIO_TEL FOREIGN KEY(ID_FUNCIONARIO_TEL) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

