CREATE DATABASE ESTUDO_CASO00005;

USE ESTUDO_CASO00005;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLIENTES_CPF VARCHAR(20) PRIMARY KEY NOT NULL,
CLIENTES_DATANASC DATE NOT NULL,
CLIENTES_RUA VARCHAR(40) NOT NULL,
CLIENTES_N_RUA INT,
CLIENTES_BAIRRO VARCHAR(80) NOT NULL,
CLIENTES_CIDADE VARCHAR(80) NOT NULL,
CLIENTES_ESTADO VARCHAR(80) NOT NULL, 
CLIENTES_PAIS VARCHAR(80) NOT NULL,
CLIENTES_CODPOSTAL VARCHAR(10) NOT NULL
);

ALTER TABLE CLIENTES ADD CLIENTES_EMAIL VARCHAR(20) NOT NULL;
ALTER TABLE CLIENTES MODIFY COLUMN CLIENTES_EMAIL VARCHAR(50);
ALTER TABLE CLIENTES CHANGE COLUMN CLIENTES_EMAIL CLIENTES_MENSAGENS_VIRTUAIS VARCHAR(50);
ALTER TABLE CLIENTES DROP COLUMN CLIENTES_MENSAGENS_VIRTUAIS;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_COD INT PRIMARY KEY NOT NULL,
FORN_CONTATO VARCHAR(50) NOT NULL,
FORN_NOME VARCHAR(80) NOT NULL,
FORN_RUA VARCHAR(40) NOT NULL,
FORN_N_RUA INT,
FORN_BAIRRO VARCHAR(80) NOT NULL,
FORN_CIDADE VARCHAR(80) NOT NULL,
FORN_ESTADO VARCHAR(80) NOT NULL, 
FORN_PAIS VARCHAR(80) NOT NULL,
FORN_CODPOSTAL VARCHAR(10) NOT NULL
);

ALTER TABLE FORNECEDORES ADD FORN_EMAIL VARCHAR(20) NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_EMAIL VARCHAR(50);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_EMAIL FORN_MENSAGENS_VIRTUAIS VARCHAR(50);
ALTER TABLE FORNECEDORES DROP COLUMN FORN_MENSAGENS_VIRTUAIS;

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY NOT NULL,
PROD_NOME VARCHAR(100) NOT NULL,
PROD_PRECO DECIMAL(10,2) NOT NULL,
PROD_QT INT 
);

ALTER TABLE PRODUTOS ADD PROD_DESCONTO VARCHAR(20) NOT NULL;
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_DESCONTO DECIMAL(10,2);
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_DESCONTO PROD_ABATIMENTO DECIMAL(10,2);
ALTER TABLE PRODUTOS DROP COLUMN PROD_ABATIMENTO;

CREATE TABLE IF NOT EXISTS VENDAS(
VENDAS_COD INT PRIMARY KEY NOT NULL,
CLIENTES_CPF VARCHAR(20) NOT NULL,
CONSTRAINT FK_CLIENTES_CPF FOREIGN KEY (CLIENTES_CPF) REFERENCES CLIENTES(CLIENTES_CPF)
);

ALTER TABLE VENDAS ADD VENDAS_VALOR VARCHAR(20) NOT NULL;
ALTER TABLE VENDAS MODIFY COLUMN VENDAS_VALOR INT;
ALTER TABLE VENDAS CHANGE COLUMN VENDAS_VALOR VENDAS_PRECO INT;
ALTER TABLE VENDAS DROP COLUMN VENDAS_PRECO;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_COD INT PRIMARY KEY NOT NULL,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_STATUS VARCHAR(50) NOT NULL,
PAG_FORMA VARCHAR(20) NOT NULL,
PAG_VENDAS_COD INT NOT NULL,
CONSTRAINT FK_PAG_VENDAS_COD FOREIGN KEY (PAG_VENDAS_COD) REFERENCES VENDAS(VENDAS_COD)
);

ALTER TABLE PAGAMENTOS ADD PAG_DESCONTO VARCHAR(20) NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_DESCONTO VARCHAR(50);
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_DESCONTO PAG_ABATIMENTO VARCHAR(50);
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_ABATIMENTO;

CREATE TABLE IF NOT EXISTS PROD_VENDAS(
PRVE_QT INT NOT NULL,
PRVE_VALOR DECIMAL(10,2) NOT NULL,
PRVE_PROD_COD INT NOT NULL,
PRVE_VENDAS_COD INT NOT NULL,
PRIMARY KEY( PRVE_PROD_COD, PRVE_VENDAS_COD),
CONSTRAINT FKPK_PRVE_PROD_COD FOREIGN KEY(PRVE_PROD_COD) REFERENCES PRODUTOS(PROD_COD),
CONSTRAINT FKPK_PRVE_VENDAS_COD FOREIGN KEY(PRVE_VENDAS_COD) REFERENCES VENDAS(VENDAS_COD)
);

ALTER TABLE PROD_VENDAS ADD PRVE_NOMES VARCHAR(20) NOT NULL;
ALTER TABLE PROD_VENDAS MODIFY COLUMN PRVE_NOMES VARCHAR(50);
ALTER TABLE PROD_VENDAS CHANGE COLUMN PRVE_NOMES PRVE_NAMES VARCHAR(50);
ALTER TABLE PROD_VENDAS DROP COLUMN PRVE_NAMES;

CREATE TABLE IF NOT EXISTS FORN_PROD(
FOPR_FORN_COD INT NOT NULL,
FOPR_PROD_COD INT NOT NULL,
PRIMARY KEY (FOPR_FORN_COD, FOPR_PROD_COD),
CONSTRAINT FKPK_FOPR_FORN_COD FOREIGN KEY (FOPR_FORN_COD) REFERENCES FORNECEDORES(FORN_COD),
CONSTRAINT FKPK_FOPR_PROD_COD FOREIGN KEY (FOPR_PROD_COD) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORN_PROD ADD FOPR_VALOR VARCHAR(20) NOT NULL;
ALTER TABLE FORN_PROD MODIFY COLUMN FOPR_VALOR VARCHAR(50);
ALTER TABLE FORN_PROD CHANGE COLUMN FOPR_VALOR FOPR_PRECO VARCHAR(50);
ALTER TABLE FORN_PROD DROP COLUMN FOPR_PRECO;


CREATE TABLE IF NOT EXISTS TESTE_ESTUDO_CASO_V(
TESTE_ID INT PRIMARY KEY NOT NULL,
TESTE_NOME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS TESTE_ESTUDO_CASO_V; 
