CREATE DATABASE ESTUDO_CASO00002;

USE ESTUDO_CASO00002;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(15) PRIMARY KEY NOT NULL,
PASS_NOME VARCHAR(60) NOT NULL,
PASS_TELEFONE VARCHAR(30) NOT NULL,
PASS_RUA VARCHAR(40) NOT NULL,
PASS_N_RUA INT,
PASS_BAIRRO VARCHAR(50) NOT NULL, 
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_ESTADO VARCHAR(50) NOT NULL,
PASS_PAIS VARCHAR(30) NOT NULL,
PASS_COD_POSTAL VARCHAR(10) NOT NULL,
PASS_EMAIL VARCHAR(100) NOT NULL
);

ALTER TABLE PASSAGEIROS ADD PASS_CEP VARCHAR(50) NOT NULL;
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_CEP VARCHAR(80);
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_CEP PASS_CODIGO_LUGAR VARCHAR(80);
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_CODIGO_LUGAR;


CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD VARCHAR(50) PRIMARY KEY NOT NULL,
AEROP_RUA VARCHAR(40) NOT NULL,
AEROP_N_RUA VARCHAR(30),
AEROP_BAIRRO VARCHAR(50) NOT NULL, 
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_ESTADO VARCHAR(50) NOT NULL,
AEROP_PAIS VARCHAR(30) NOT NULL,
AEROP_NOME VARCHAR(60) NOT NULL,
AEROP_LATITUDE DECIMAL(10,8) NOT NULL,
AEROP_LONGITUDE DECIMAL(10,8) NOT NULL 
);

ALTER TABLE AEROPORTOS ADD AEROP_CONTATO VARCHAR(80) NOT NULL;
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_CONTATO VARCHAR(90);
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_CONTATO AEROP_CONTATAR VARCHAR(90);
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_CONTATAR;


CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO VARCHAR(20) PRIMARY KEY NOT NULL, 
AERON_MODELO VARCHAR (30) NOT NULL,
AERON_ANOFABR YEAR NOT NULL,
AERON_FABRICANTE VARCHAR(40) NOT NULL,
AERON_CAPACIDADE INT NOT NULL,
AERON_AUTONOMIA DECIMAL(5,4) NOT NULL
);

ALTER TABLE AERONAVES ADD AERON_VALOR DECIMAL(10,2) NOT NULL;
ALTER TABLE AERONAVES MODIFY COLUMN AERON_VALOR VARCHAR(80);
ALTER TABLE AERONAVES CHANGE COLUMN AERON_VALOR AERON_VALOR_PAGO VARCHAR(80);
ALTER TABLE AERONAVES DROP COLUMN AERON_VALOR_PAGO;


CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY NOT NULL, 
FUNC_NOME VARCHAR(60) NOT NULL,
FUNC_TELEFONE VARCHAR(30) NOT NULL,
FUNC_RUA VARCHAR(40) NOT NULL,
FUNC_N_RUA INT,
FUNC_BAIRRO VARCHAR(50) NOT NULL, 
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_ESTADO VARCHAR(50) NOT NULL,
FUNC_PAIS VARCHAR(30) NOT NULL,
FUNC_DATANASC DATE NOT NULL, 
FUNC_CPF VARCHAR (30) NOT NULL,
FUNC_FUNCAO VARCHAR(40) NOT NULL 
);

ALTER TABLE FUNCIONARIOS ADD FUNC_EMAIL VARCHAR(20) NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_EMAIL VARCHAR(50);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_EMAIL FUNC_MENSAGENS_VIRTUAIS VARCHAR(50);
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_MENSAGENS_VIRTUAIS;


CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY NOT NULL,
VOO_DATA DATE NOT NULL, 
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM VARCHAR(50) NOT NULL,
VOO_AEROP_DESTINO VARCHAR(50) NOT NULL,
VOO_AERONAVE VARCHAR(10) NOT NULL, 
CONSTRAINT VOO_AEROP_FKPK_ORIGEM FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT VOO_AEROP_FKPK_DESTINO FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_COD),
CONSTRAINT VOO_FKPK_AERONAVE FOREIGN KEY (VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

ALTER TABLE VOOS ADD VOO_QUANT_OBJETOS VARCHAR(20) NOT NULL;
ALTER TABLE VOOS MODIFY COLUMN VOO_QUANT_OBJETOS INT;
ALTER TABLE VOOS CHANGE COLUMN VOO_QUANT_OBJETOS VOO_CAPACIDADE INT;
ALTER TABLE VOOS DROP COLUMN VOO_CAPACIDADE;


CREATE TABLE IF NOT EXISTS RESERVAS(
RESERVA_COD INT PRIMARY KEY NOT NULL,
VOO_RESERVA INT NOT NULL, 
PASS_RESERVA VARCHAR(10) NOT NULL,
CONSTRAINT FK_VOO_ID FOREIGN KEY (VOO_RESERVA) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_PASS_CPF FOREIGN KEY (PASS_RESERVA) REFERENCES PASSAGEIROS(PASS_CPF)
);

ALTER TABLE RESERVAS ADD RESERVA_PLATAFORMA_COMPRA VARCHAR(20) NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN RESERVA_PLATAFORMA_COMPRA VARCHAR(50);
ALTER TABLE RESERVAS CHANGE COLUMN RESERVA_PLATAFORMA_COMPRA RESERVA_LUGAR_COMPRA VARCHAR(50);
ALTER TABLE RESERVAS DROP COLUMN RESERVA_LUGAR_COMPRA;


CREATE TABLE IF NOT EXISTS EQUIPES(
FUNC_EQUIPES INT NOT NULL,
VOO_EQUIPES INT NOT NULL,
PRIMARY KEY (FUNC_EQUIPES, VOO_EQUIPES), 
CONSTRAINT FKPK_FUNC_EQUIPES FOREIGN KEY(FUNC_EQUIPES) REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT FKPK_VOO_EQUIPES FOREIGN KEY (VOO_EQUIPES) REFERENCES VOOS(VOO_ID)
);

ALTER TABLE EQUIPES ADD EQUIPES_NOMES VARCHAR(80) NOT NULL;
ALTER TABLE EQUIPES MODIFY COLUMN EQUIPES_NOMES VARCHAR(100);
ALTER TABLE EQUIPES CHANGE COLUMN EQUIPES_NOMES EQUIPES_NAMES VARCHAR(100);
ALTER TABLE EQUIPES DROP COLUMN EQUIPES_NAMES;

CREATE TABLE IF NOT EXISTS TESTE_CASO_II(
TESTE_ID INT PRIMARY KEY NOT NULL,
TESTE_NOME VARCHAR(80) NOT NULL
);

DROP TABLE IF EXISTS TESTE_CASO_II;

