CREATE DATABASE ESTUDO_CASO00001;

USE ESTUDO_CASO00001; 

CREATE TABLE IF NOT EXISTS FORNECEDORES( 
FORN_COD INT PRIMARY KEY NOT NULL,
FORN_NOME VARCHAR(30) NOT NULL,
FORN_RUA VARCHAR(45) NOT NULL,
FORN_N_RUA INT, 
FORN_BAIRRO VARCHAR(40) NOT NULL,
FORN_CIDADE VARCHAR(40) NOT NULL,
FORN_ESTADO VARCHAR(40) NOT NULL,
FORN_PAIS VARCHAR(30) NOT NULL,
FORN_COD_POSTAL VARCHAR(15) NOT NULL,
FORN_TELEFONE VARCHAR(20) NOT NULL,
FORN_CONTATO TEXT NOT NULL
); 

ALTER TABLE FORNECEDORES ADD FORN_EMAIL VARCHAR(20) NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_EMAIL VARCHAR(50);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_EMAIL FORN_MENSAGENS_VIRTUAIS VARCHAR(50);
ALTER TABLE FORNECEDORES DROP COLUMN FORN_MENSAGENS_VIRTUAIS;


CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY NOT NULL,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPETEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDADEMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQUE_MIN DECIMAL(10,3) NOT NULL
);

ALTER TABLE PRODUTOS ADD PROD_VALOR INT NOT NULL;
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_VALOR DECIMAL(10,2);
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_VALOR PROD_DINHEIRO_PAGO DECIMAL(10,2);
ALTER TABLE PRODUTOS DROP COLUMN PROD_DINHEIRO_PAGO;


CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAIS_COD INT PRIMARY KEY NOT NULL,
FILIAIS_NOME VARCHAR(30) NOT NULL,
FILIAIS_RUA VARCHAR(30) NOT NULL,
FILIAIS_N_RUA INT NOT NULL,
FILIAIS_BAIRRO VARCHAR(50) NOT NULL,
FILIAIS_CIDADE VARCHAR(50) NOT NULL,
FILIAIS_ESTADO VARCHAR(50) NOT NULL,
FILIAIS_PAIS VARCHAR(50) NOT NULL,
FILIAIS_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAIS_CAPACIDADE VARCHAR(50) NOT NULL
);

ALTER TABLE FILIAIS ADD FILIAIS_CEP VARCHAR(80) NOT NULL;
ALTER TABLE FILIAIS MODIFY COLUMN FILIAIS_CEP VARCHAR(90);
ALTER TABLE FILIAIS CHANGE COLUMN FILIAIS_CEP FILIAIS_C_E_P VARCHAR(90);
ALTER TABLE FILIAIS DROP COLUMN FILIAIS_C_E_P;


CREATE TABLE IF NOT EXISTS PEDIDOS(
PEDIDOS_COD INT PRIMARY KEY NOT NULL,
PEDIDOS_DATA DATE NOT NULL,
PEDIDOS_HORA TIME NOT NULL,
PEDIDOS_PREVISAO DATE NOT NULL,
PEDIDOS_STATUS VARCHAR(20) NOT NULL, 
FORN_PEDIDO INT NOT NULL, 
CONSTRAINT FK_FORN_PEDIDO FOREIGN KEY(FORN_PEDIDO) REFERENCES FORNECEDORES(FORN_COD) 
);

ALTER TABLE PEDIDOS ADD PEDIDOS_HORA_CHEGADA TIME  NOT NULL;
ALTER TABLE PEDIDOS MODIFY COLUMN PEDIDOS_HORA_CHEGADA VARCHAR(90);
ALTER TABLE PEDIDOS CHANGE COLUMN PEDIDOS_HORA_CHEGADA PEDIDOS_HORA_CHEGAR VARCHAR(90);
ALTER TABLE PEDIDOS DROP COLUMN PEDIDOS_HORA_CHEGAR;


CREATE TABLE IF NOT EXISTS PED_PROD(
PDPR_PED INT NOT NULL,
PDPR_PROD INT NOT NULL,
PRIMARY KEY(PDPR_PED, PDPR_PROD), 
CONSTRAINT PDPR_FKPK_PED FOREIGN KEY (PDPR_PED) REFERENCES PEDIDOS(PEDIDOS_COD),
CONSTRAINT PDPR_FKPK_PROD FOREIGN KEY (PDPR_PROD) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE PED_PROD ADD PDPR_STATUS VARCHAR(40) NOT NULL;
ALTER TABLE PED_PROD MODIFY COLUMN PDPR_STATUS VARCHAR(50);
ALTER TABLE PED_PROD CHANGE COLUMN PDPR_STATUS PDPR_COMO_ESTA VARCHAR(50);
ALTER TABLE PED_PROD DROP COLUMN PDPR_COMO_ESTA;

CREATE TABLE IF NOT EXISTS FILIAIS_PROD(
FLPR_FIL INT NOT NULL,
FLPR_PROD INT NOT NULL,
PRIMARY KEY (FLPR_FIL, FLPR_PROD),
CONSTRAINT FLPR_FKPK_FIL FOREIGN KEY (FLPR_FIL) REFERENCES FILIAIS(FILIAIS_COD),
CONSTRAINT FLPR_FKPK_PROD FOREIGN KEY (FLPR_PROD) REFERENCES PRODUTOS(PROD_COD)  
);

ALTER TABLE FILIAIS_PROD ADD FLPR_NOMES VARCHAR(20) NOT NULL;
ALTER TABLE FILIAIS_PROD MODIFY COLUMN FLPR_NOMES VARCHAR(80);
ALTER TABLE FILIAIS_PROD CHANGE COLUMN FLPR_NOMES FLPR_SOBRENOME VARCHAR(80);
ALTER TABLE FILIAIS_PROD DROP COLUMN FLPR_SOBRENOME;


CREATE TABLE IF NOT EXISTS FORN_PROD(
FOPR_FORN INT NOT NULL,
FOPR_PROD INT NOT NULL, 
CONSTRAINT FOPR_FKPK_FORN FOREIGN KEY (FOPR_FORN) REFERENCES FORNECEDORES(FORN_COD),
CONSTRAINT FOPR_FKPR_PROD FOREIGN KEY (FOPR_PROD) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORN_PROD ADD FOPR_QUANT_OBJETOS VARCHAR(20) NOT NULL;
ALTER TABLE FORN_PROD MODIFY COLUMN FOPR_QUANT_OBJETOS INT;
ALTER TABLE FORN_PROD CHANGE COLUMN FOPR_QUANT_OBJETOS FOPR_COISAS INT;
ALTER TABLE FORN_PROD DROP COLUMN FOPR_COISAS;

CREATE TABLE IF NOT EXISTS TESTE_CASO_I (
TESTE_ID INT PRIMARY KEY NOT NULL,
TESTE_NOME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS TESTE_CASO_I
