CREATE DATABASE ESTUDO_CASO00003;

USE ESTUDO_CASO00003;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLIENTE_COD INT PRIMARY KEY NOT NULL,
CLIENTE_CNPJ VARCHAR(15) NOT NULL,
CLIENTE_RAZAO_SOCIAL VARCHAR(15) NOT NULL,
CLIENTE_RAMO_ATIVIDADE VARCHAR(30) NOT NULL,
CLIENTE_DATA_CADASTRAMENTO DATE NOT NULL, 
CLIENTE_PESSOACONTAT VARCHAR(20) NOT NULL
);

ALTER TABLE CLIENTES ADD CLIENTE_EMAIL VARCHAR(20) NOT NULL;
ALTER TABLE CLIENTES MODIFY COLUMN CLIENTE_EMAIL VARCHAR(50);
ALTER TABLE CLIENTES CHANGE COLUMN CLIENTE_EMAIL CLIENTE_MENSAGENS_VIRTUAIS VARCHAR(50);
ALTER TABLE CLIENTES DROP COLUMN CLIENTE_MENSAGENS_VIRTUAIS;

CREATE TABLE IF NOT EXISTS EMPREGADOS(
EMPR_COD INT PRIMARY KEY NOT NULL, 
EMPR_NOME VARCHAR(70) NOT NULL, 
EMPR_CARGO VARCHAR(20) NOT NULL, 
EMPR_SALARIO DECIMAL(8,5) NOT NULL, 
EMPR_DATEADMI DATE NOT NULL, 
EMPR_QUALIFICACOES VARCHAR(30) NOT NULL
); 

ALTER TABLE EMPREGADOS ADD EMPR_EMAIL VARCHAR(20) NOT NULL;
ALTER TABLE EMPREGADOS MODIFY COLUMN EMPR_EMAIL VARCHAR(50);
ALTER TABLE EMPREGADOS CHANGE COLUMN EMPR_EMAIL EMPR_MENSAGENS_VIRTUAIS VARCHAR(50);
ALTER TABLE EMPREGADOS DROP COLUMN EMPR_MENSAGENS_VIRTUAIS;


CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_CNPJ VARCHAR(20) PRIMARY KEY NOT NULL,
FORN_RAZAO_SOCIAL VARCHAR(30) NOT NULL, 
FORN_PESSOACONT VARCHAR(70) NOT NULL
);

ALTER TABLE FORNECEDORES ADD FORN_DATANASC DATE NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_DATANASC VARCHAR(50);
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_DATANASC FORN_HORA_QUE_CHEGOU_AO_MUNDO VARCHAR(50);
ALTER TABLE FORNECEDORES DROP COLUMN FORN_HORA_QUE_CHEGOU_AO_MUNDO;

CREATE TABLE IF NOT EXISTS MAQUINAS(
MAQUINAS_COD INT PRIMARY KEY NOT NULL, 
MAQUINAS_TEMPODEVIDA DATE NOT NULL,
MAQUINAS_DATACOMPRA DATE NOT NULL,
MAQUINAS_FIMDEGARANTIA DATE NOT NULL
);

ALTER TABLE MAQUINAS ADD MAQUINAS_NOME VARCHAR(80) NOT NULL;
ALTER TABLE MAQUINAS MODIFY COLUMN MAQUINAS_NOME VARCHAR(100);
ALTER TABLE MAQUINAS CHANGE COLUMN MAQUINAS_NOME MAQUINAS_ALCUNHA VARCHAR(100);
ALTER TABLE MAQUINAS DROP COLUMN MAQUINAS_ALCUNHA;

CREATE TABLE IF NOT EXISTS TIPOCOMP(
TDC_COD INT PRIMARY KEY NOT NULL, 
TDC_NOME VARCHAR(100) NOT NULL
);

ALTER TABLE TIPOCOMP ADD TDC_QUANT INT NOT NULL;
ALTER TABLE TIPOCOMP MODIFY COLUMN TDC_QUANT VARCHAR(50);
ALTER TABLE TIPOCOMP CHANGE COLUMN TDC_QUANT TDC_ABUNDANCIA VARCHAR(50);
ALTER TABLE TIPOCOMP DROP COLUMN TDC_ABUNDANCIA;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAGAMENTOS_ID INT PRIMARY KEY NOT NULL, 
PAGAMENTOS_TOTAL DECIMAL(10,2),
PAGAMENTOS_DESCONTO DECIMAL(10,2),
PAGAMENTOS_LIQUIDO DECIMAL(10,2),
PAGAMENTOS_FORMAPAG VARCHAR(30) NOT NULL, 
PAGAMENTOS_QUANTPARCELAS VARCHAR(30) NOT NULL
);

ALTER TABLE PAGAMENTOS ADD PAGAMENTOS_DIA DATE NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAGAMENTOS_DIA VARCHAR(50);
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAGAMENTOS_DIA PAGAMENTOS_DATA VARCHAR(50);
ALTER TABLE PAGAMENTOS DROP COLUMN PAGAMENTOS_DATA;

CREATE TABLE IF NOT EXISTS COMPONENTES(
COMP_COD INT PRIMARY KEY NOT NULL, 
COMP_NOME VARCHAR(100) NOT NULL,
COMP_QUANTESTOQUE INT NOT NULL,
COMP_PRECOUNIT DECIMAL(10,1) NOT NULL,
COMP_UND DECIMAL(5,2)
);

ALTER TABLE COMPONENTES ADD COMP_VALOR DECIMAL(10,2) NOT NULL;
ALTER TABLE COMPONENTES MODIFY COLUMN COMP_VALOR VARCHAR(50);
ALTER TABLE COMPONENTES CHANGE COLUMN COMP_VALOR COMP_PRECO_PAGO VARCHAR(50);
ALTER TABLE COMPONENTES DROP COLUMN COMP_PRECO_PAGO;

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY NOT NULL,
PROD_NOME VARCHAR(50) NOT NULL, 
PROD_COR VARCHAR(15) NOT NULL,
PROD_DIMENSOES DECIMAL(8,3) NOT NULL,
PROD_PESO DECIMAL(10,2) NOT NULL,
PROD_TEMPODEFABR TIME NOT NULL,
PROD_HORAOBRA TIME NOT NULL
); 

ALTER TABLE PRODUTOS ADD PROD_QUANT INT NOT NULL;
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_QUANT VARCHAR(50);
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_QUANT PROD_ABUNDANCIA VARCHAR(50);
ALTER TABLE PRODUTOS DROP COLUMN PROD_ABUNDANCIA;


CREATE TABLE IF NOT EXISTS TIPO_END(
TDE_COD INT PRIMARY KEY NOT NULL,
TDE_NOME VARCHAR(100) NOT NULL,
T_CLIENTE_COD INT NOT NULL,
T_EMPR_COD INT NOT NULL, 
T_FORN_CNPJ VARCHAR(20) NOT NULL,
CONSTRAINT FK_T_CLIENTE_COD FOREIGN KEY (T_CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD),
CONSTRAINT FK_T_EMPR_COD FOREIGN KEY (T_EMPR_COD) REFERENCES EMPREGADOS(EMPR_COD),
CONSTRAINT FK_T_FORN_CNPJ FOREIGN KEY (T_FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ)
);

ALTER TABLE TIPO_END ADD TDE_COMPLEMENTOS VARCHAR(80) NOT NULL;
ALTER TABLE TIPO_END MODIFY COLUMN TDE_COMPLEMENTOS VARCHAR(100);
ALTER TABLE TIPO_END CHANGE COLUMN TDE_COMPLEMENTOS TDE_REFERENCIAS VARCHAR(50);
ALTER TABLE TIPO_END DROP COLUMN TDE_REFERENCIAS;


CREATE TABLE IF NOT EXISTS ENDERECOS(
ENDERECOS_RUA VARCHAR(50) NOT NULL,
ENDERECOS_N_RUA VARCHAR(10),
ENDERECOS_COMPLEMENTOS VARCHAR(40),
ENDERECOS_CEP VARCHAR(15) NOT NULL,
ENDERECOS_BAIRRO VARCHAR(30) NOT NULL,
ENDERECOS_CIDADE VARCHAR(30) NOT NULL,
ENDERECOS_PAIS VARCHAR(20) NOT NULL,
TDE_EMPR_COD INT NOT NULL,
TDE_FORN_CNPJ VARCHAR(20) NOT NULL, 
TDE_CLIENTE_COD INT NOT NULL, 
CONSTRAINT FK_TDE_CLIENTE_COD FOREIGN KEY (TDE_CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD),
CONSTRAINT FK_TDE_EMPR_COD FOREIGN KEY (TDE_EMPR_COD) REFERENCES EMPREGADOS(EMPR_COD),
CONSTRAINT FK_TDE_FORN_CNPJ FOREIGN KEY (TDE_FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ)
);

ALTER TABLE ENDERECOS ADD ENDERECOS_NOME VARCHAR(90) NOT NULL;
ALTER TABLE ENDERECOS MODIFY COLUMN ENDERECOS_NOME VARCHAR(100);
ALTER TABLE ENDERECOS CHANGE COLUMN ENDERECOS_NOME ENDERECO_COMO_SAO_CHAMADOS VARCHAR(50);
ALTER TABLE ENDERECOS DROP COLUMN ENDERECO_COMO_SAO_CHAMADOS;


CREATE TABLE IF NOT EXISTS RS(
RS_QUANT INT NOT NULL,
RS_DESCRICAO VARCHAR(80) NOT NULL,
MAQUINAS_COD INT NOT NULL, 
COMP_COD INT NOT NULL,
PRIMARY KEY ( MAQUINAS_COD, COMP_COD),
CONSTRAINT FKPK_MAQUINAS_COD FOREIGN KEY (MAQUINAS_COD) REFERENCES MAQUINAS(MAQUINAS_COD),
CONSTRAINT FKPK_COMP_COD FOREIGN KEY (COMP_COD) REFERENCES COMPONENTES(COMP_COD)
);

ALTER TABLE RS ADD RS_DIA DATE NOT NULL;
ALTER TABLE RS MODIFY COLUMN RS_DIA VARCHAR(50);
ALTER TABLE RS CHANGE COLUMN RS_DIA RS_DATA VARCHAR(50);
ALTER TABLE RS DROP COLUMN RS_DATA;

CREATE TABLE IF NOT EXISTS RE(
RE_QUANTNECESSARIA DECIMAL(8,3) NOT NULL, 
RE_UND VARCHAR(30) NOT NULL,
RE_TEMPOUSO TIME NOT NULL,
RE_HORAS_OBRA TIME NOT NULL,
PROD_COD INT NOT NULL,
CONSTRAINT FK_PROD_COD FOREIGN KEY (PROD_COD) REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE RE ADD RE_NOMESPROD VARCHAR(80) NOT NULL;
ALTER TABLE RE MODIFY COLUMN RE_NOMESPROD VARCHAR(100);
ALTER TABLE RE CHANGE COLUMN RE_NOMESPROD RE_NAMES VARCHAR(100);
ALTER TABLE RE DROP COLUMN RE_NAMES;


CREATE TABLE IF NOT EXISTS RM(
RM_DATA DATE NOT NULL,
RM_DESCRICAO VARCHAR(70) NOT NULL,
MAQUINAS_COD INT NOT NULL, 
CONSTRAINT FK_MAQUINAS_COD FOREIGN KEY (MAQUINAS_COD) REFERENCES MAQUINAS(MAQUINAS_COD)
);

ALTER TABLE RM ADD RM_QUANTTRABALHADORES INT NOT NULL;
ALTER TABLE RM MODIFY COLUMN RM_QUANTTRABALHADORES VARCHAR(50);
ALTER TABLE RM CHANGE COLUMN RM_QUANTTRABALHADORES RM_N_TRABALHADORES VARCHAR(50);
ALTER TABLE RM DROP COLUMN RM_N_TRABALHADORES;


CREATE TABLE IF NOT EXISTS TELEFONE(
TEL_DDD INT NOT NULL,
TEL_NUM VARCHAR(20) NOT NULL,
CLIENTE_COD INT NOT NULL,
EMPR_COD INT NOT NULL,
FORN_CNPJ VARCHAR(20) NOT NULL,
CONSTRAINT FK_CLIENTE_COD FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTES(CLIENTE_COD),
CONSTRAINT FK_EMPR_COD FOREIGN KEY (EMPR_COD) REFERENCES EMPREGADOS(EMPR_COD),
CONSTRAINT FK_FORN_CNPJ FOREIGN KEY (FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ)
);

ALTER TABLE TELEFONE ADD TEL_OPERADORA VARCHAR(30) NOT NULL;
ALTER TABLE TELEFONE MODIFY COLUMN TEL_OPERADORA VARCHAR(50);
ALTER TABLE TELEFONE CHANGE COLUMN TEL_OPERADORA TEL_NOME_OPERADORA VARCHAR(50);
ALTER TABLE TELEFONE DROP COLUMN TEL_NOME_OPERADORA;


CREATE TABLE IF NOT EXISTS FORN_COMP(
FRCM_COMP_COD INT NOT NULL,
FRCM_FORN_CNPJ VARCHAR(20) NOT NULL, 
PRIMARY KEY (FRCM_COMP_COD, FRCM_FORN_CNPJ),
CONSTRAINT FKPK_FRCM_COMP_COD FOREIGN KEY (FRCM_COMP_COD) REFERENCES COMPONENTES(COMP_COD),
CONSTRAINT FKPK_FRCM_FORN_CNPJ FOREIGN KEY (FRCM_FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ)
);

ALTER TABLE FORN_COMP ADD FRCM_NOMES VARCHAR(80) NOT NULL;
ALTER TABLE FORN_COMP MODIFY COLUMN FRCM_NOMES VARCHAR(100);
ALTER TABLE FORN_COMP CHANGE COLUMN FRCM_NOMES FRCM_NAMES VARCHAR(100);
ALTER TABLE FORN_COMP DROP COLUMN FRCM_NAMES;

CREATE TABLE IF NOT EXISTS TESTE_ESTUDO_CASO_III(
TESTE_ID INT PRIMARY KEY NOT NULL,
TESTE_NOME VARCHAR(80) NOT NULL
);

DROP TABLE IF EXISTS TESTE_ESTUDO_CASO_III
